version: '3'
services:
  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork
    volumes:
      - ./.redis-data:/data # 持久化
networks:
  mynetwork:
    driver: bridge