# 线上配置文件
server:
  port: 8101
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://gz-cdb-ns8hvyw3.sql.tencentcdb.com:29720/qioj?useSSL=false&serverTimezone=GMT&characterEncoding=UTF-8
    username: root
    password: wuqian2002@
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: redis
    port: 6379
    timeout: 5000
#    password: 123456
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
# 代码沙箱配置
codesandbox:
  type: remote